package com.harvey.arcfacedamo.db.dao;

import com.harvey.arcfacedamo.db.bean.FaceRegister;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig faceRegisterDaoConfig;

    private final FaceRegisterDao faceRegisterDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        faceRegisterDaoConfig = daoConfigMap.get(FaceRegisterDao.class).clone();
        faceRegisterDaoConfig.initIdentityScope(type);

        faceRegisterDao = new FaceRegisterDao(faceRegisterDaoConfig, this);

        registerDao(FaceRegister.class, faceRegisterDao);
    }
    
    public void clear() {
        faceRegisterDaoConfig.clearIdentityScope();
    }

    public FaceRegisterDao getFaceRegisterDao() {
        return faceRegisterDao;
    }

}
